# Generated by Django 4.0.4 on 2022-04-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Domain', models.CharField(help_text='Do Not Use Prefix Like http:// Or https:', max_length=255, unique=True)),
                ('Location', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(help_text='Phone Number', max_length=10)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('BelongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Organization')),
            ],
        ),
    ]
