# Generated by Django 4.0.4 on 2022-04-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAPIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApiKeys', models.ManyToManyField(to='apikey.apikey')),
                ('Appication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.application')),
            ],
        ),
    ]
