# Generated by Django 4.0.4 on 2022-04-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=1000)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('BlackListed', models.BooleanField(default=False)),
                ('BelongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.application', verbose_name='Application')),
            ],
        ),
    ]
